# hash:sha256:5ab30cb8f13dd634b328584640da2d848f99312ff3d0a6086a25f5b67d77f7e4
FROM localhost:5000/codeocean/miniconda3:4.7.10-python3.7-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
