# hash:sha256:e4f2b4fb0f9149ba68fcad4de13e6f1c0b9c9e4496c5a6c9dc6dde2858e8a24e
FROM registry.rc-apsoutheast2.acmecorp.codeocean.dev/codeocean/jupyterlab:3.4.4-miniconda4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
